# Generated by Django 4.2.3 on 2023-08-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
