# Generated by Django 4.2.3 on 2023-08-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0003_create_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptRankingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.CharField(max_length=50)),
                ('prompt_rankings', models.TextField(default='{}')),
            ],
        ),
    ]
